name: Docker Image Build and Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry (GHCR)
      run: |
        docker login --username ${{ github.actor }}  --password ${{ secrets.TOKEN_GITHUB }} ghcr.io

    - name: Build Docker Image
      run: |
        # Build the Docker image and tag it with the Git commit SHA and 'latest'
        docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }} .
        docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest .

    - name: Push Docker Image to GHCR
      run: |
        # Push the Docker image to GitHub Container Registry
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.TOKEN_GITHUB }}" \
          -d "{\"tag_name\":\"${{ github.ref }}\",\"name\":\"Release ${{ github.ref }}\",\"body\":\"Release of Docker image for ${{ github.ref }}\",\"draft\":false,\"prerelease\":false}" \
          https://api.github.com/repos/${{ github.repository }}/releases
