name: Docker Image CI hai

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}             # GitHub username (authenticated user)
        password: ${{ secrets.TOKEN_GITHUB }}     # GitHub token to authenticate (this will be used for GHCR)

    - name: Build Docker Image
      run: |
        # Build the Docker image and tag it with the Git commit SHA and 'latest'
        docker build -t ghcr.io/${{ github.repository_owner }}/redditvideobot:${{ github.sha }} .
        docker build -t ghcr.io/${{ github.repository_owner }}/redditvideobot:latest .

    - name: Push Docker Image to GHCR
      run: |
        # Push the Docker image to GitHub Container Registry
        docker push ghcr.io/${{ github.repository_owner }}/redditvideobot:${{ github.sha }}
        docker push ghcr.io/${{ github.repository_owner }}/redditvideobot:latest

    - name: Create GitHub Release (Optional)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d "{\"tag_name\":\"${{ github.ref }}\",\"name\":\"Release ${{ github.ref }}\",\"body\":\"Release of Docker image for ${{ github.ref }}\",\"draft\":false,\"prerelease\":false}" \
          https://api.github.com/repos/${{ github.repository }}/releases
